'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import DraftPreview from '@/components/content/DraftPreview';
import OpportunityList from '@/components/content/OpportunityList';
import PublishJobList from '@/components/content/PublishJobList';
import {
  fetchPipelineSession,
  loginPipeline,
  logoutPipeline,
  SESSION_AUTH_PLACEHOLDER,
} from '@/lib/client/pipeline-auth';
import {
  autoGenerateDraft,
  computeRealtimeOpportunities,
  generateDraft,
  generateRealtimeDraft,
  getAccountProfile,
  getDraftSynthesisReport,
  getDraftDetail,
  listAccounts,
  listOpportunities,
  planDraftAssets,
  publishWechatDraft,
  regenerateDraft,
  retryPublishJob,
  rollbackAccountProfile,
  updateAccountProfile,
} from '@/lib/client/pipeline-api';
import type {
  AccountProfileInput,
  DraftSynthesisReportData,
  OpportunityItem,
  OpportunityStatus,
  Pagination,
  RealtimeOpportunityComputeData,
} from '@/types/content-ui';
import type { AccountProfileVersionItem, DraftDetail } from '@/types/content-ui';
import { OPPORTUNITY_STATUS_OPTIONS } from '@/types/content-ui';

const DEFAULT_PAGE_SIZE = 12;

interface BannerState {
  type: 'success' | 'error' | 'info';
  text: string;
}

interface ProfileFormState {
  audience: string;
  tone: string;
  growthGoal: string;
  painPoints: string;
  contentPromise: string;
  forbiddenTopics: string;
  ctaStyle: string;
  preferredLength: number;
}

const EMPTY_PROFILE: ProfileFormState = {
  audience: '',
  tone: '',
  growthGoal: 'read',
  painPoints: '',
  contentPromise: '',
  forbiddenTopics: '',
  ctaStyle: '',
  preferredLength: 1800,
};

function bannerClass(type: BannerState['type']) {
  if (type === 'success') {
    return 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200';
  }
  if (type === 'error') {
    return 'border-red-200 bg-red-50 text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-200';
  }
  return 'border-indigo-200 bg-indigo-50 text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-500/10 dark:text-indigo-200';
}

function toCsv(values: string[] | undefined) {
  if (!values || values.length === 0) return '';
  return values.join('；');
}

function splitList(input: string) {
  return Array.from(new Set(input.split(/[；;，,\n]/).map((item) => item.trim()).filter(Boolean)));
}

function mapProfileForm(input: AccountProfileInput): ProfileFormState {
  return {
    audience: input.audience,
    tone: input.tone,
    growthGoal: input.growthGoal,
    painPoints: toCsv(input.painPoints),
    contentPromise: input.contentPromise || '',
    forbiddenTopics: toCsv(input.forbiddenTopics),
    ctaStyle: input.ctaStyle || '',
    preferredLength: input.preferredLength,
  };
}

function buildProfilePayload(form: ProfileFormState): AccountProfileInput {
  return {
    audience: form.audience.trim(),
    tone: form.tone.trim(),
    growthGoal: form.growthGoal.trim() || 'read',
    painPoints: splitList(form.painPoints),
    contentPromise: form.contentPromise.trim() || undefined,
    forbiddenTopics: splitList(form.forbiddenTopics),
    ctaStyle: form.ctaStyle.trim() || undefined,
    preferredLength: Math.min(3000, Math.max(800, Math.round(form.preferredLength || 1800))),
  };
}

function formatTime(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '-';
  return date.toLocaleString('zh-CN', {
    hour12: false, month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
  });
}

export default function ContentPipelinePanel() {
  const [apiSecret, setApiSecret] = useState('');
  const [loginUsername, setLoginUsername] = useState('');
  const [loginPassword, setLoginPassword] = useState('');
  const [authChecking, setAuthChecking] = useState(true);
  const [authSubmitting, setAuthSubmitting] = useState(false);
  const [authUser, setAuthUser] = useState<string | null>(null);
  const [realtimeTopN, setRealtimeTopN] = useState(50);
  const [showAccountSettings, setShowAccountSettings] = useState(false);

  const [statusFilter, setStatusFilter] = useState<OpportunityStatus>('NEW');
  const [accountIdFilter, setAccountIdFilter] = useState('');
  const [opportunities, setOpportunities] = useState<OpportunityItem[]>([]);
  const [pagination, setPagination] = useState<Pagination | null>(null);
  const [accounts, setAccounts] = useState<Array<{ id: string; name: string; platform: string }>>([]);

  const [selectedOpportunityId, setSelectedOpportunityId] = useState<string | null>(null);
  const [selectedAccountId, setSelectedAccountId] = useState<string>('');
  const [draft, setDraft] = useState<DraftDetail | null>(null);

  const [profileForm, setProfileForm] = useState<ProfileFormState>(EMPTY_PROFILE);
  const [profileUpdatedAt, setProfileUpdatedAt] = useState<string>('');
  const [profileVersions, setProfileVersions] = useState<AccountProfileVersionItem[]>([]);

  const [loadingOpportunities, setLoadingOpportunities] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [generatingRealtime, setGeneratingRealtime] = useState(false);
  const [generatingOpportunityId, setGeneratingOpportunityId] = useState<string | null>(null);
  const [loadingDraft, setLoadingDraft] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [retryingJobId, setRetryingJobId] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [planningAssets, setPlanningAssets] = useState(false);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [loadingProfile, setLoadingProfile] = useState(false);
  const [loadingSynthesis, setLoadingSynthesis] = useState(false);
  const [savingProfile, setSavingProfile] = useState(false);
  const [rollingBackVersionId, setRollingBackVersionId] = useState<string | null>(null);
  const [synthesisReport, setSynthesisReport] = useState<DraftSynthesisReportData | null>(null);
  const [banner, setBanner] = useState<BannerState | null>(null);
  const [realtimeSession, setRealtimeSession] = useState<RealtimeOpportunityComputeData | null>(null);

  const loadSession = useCallback(async () => {
    setAuthChecking(true);
    try {
      const session = await fetchPipelineSession();
      if (session.authenticated) {
        setAuthUser(session.username || 'admin');
        setApiSecret(SESSION_AUTH_PLACEHOLDER);
      } else {
        setAuthUser(null);
        setApiSecret('');
      }
    } catch (error) {
      setAuthUser(null);
      setApiSecret('');
      setBanner({ type: 'error', text: '身份校验失败' });
    } finally {
      setAuthChecking(false);
    }
  }, []);

  useEffect(() => { void loadSession(); }, [loadSession]);

  const selectedOpportunity = useMemo(
    () => opportunities.find((item) => item.id === selectedOpportunityId) || null,
    [opportunities, selectedOpportunityId]
  );

  useEffect(() => { setRealtimeSession(null); }, [selectedAccountId]);

  const loadAccounts = useCallback(async () => {
    if (!apiSecret.trim()) return;
    try {
      const items = await listAccounts(apiSecret.trim());
      setAccounts(items);
      if (items.length > 0) {
        const hasSelectedAccount = items.some((item) => item.id === selectedAccountId);
        if (!selectedAccountId || !hasSelectedAccount) {
          setSelectedAccountId(items[0].id);
        }
      } else {
        setSelectedAccountId('');
      }
      if (items.length === 0) {
        setBanner({ type: 'info', text: '暂无可用账号，请先配置账号定位。' });
      }
    } catch (error) {
      setBanner({ type: 'error', text: '加载账号列表失败' });
    }
  }, [apiSecret, selectedAccountId]);

  const loadProfile = useCallback(async (accountId: string) => {
    if (!apiSecret.trim() || !accountId) return;
    setLoadingProfile(true);
    try {
      const result = await getAccountProfile(apiSecret.trim(), accountId);
      setProfileForm(mapProfileForm(result.profile));
      setProfileUpdatedAt(result.profile.updatedAt);
      setProfileVersions(result.versions);
    } catch (error) {
      setBanner({ type: 'error', text: '加载定位配置失败' });
    } finally {
      setLoadingProfile(false);
    }
  }, [apiSecret]);

  useEffect(() => {
    if (apiSecret.trim() && selectedAccountId) void loadProfile(selectedAccountId);
  }, [apiSecret, selectedAccountId, loadProfile]);

  useEffect(() => {
    if (apiSecret.trim()) void loadAccounts();
  }, [apiSecret, loadAccounts]);

  async function handleLogin() {
    const username = loginUsername.trim();
    if (!username || !loginPassword) return;
    setAuthSubmitting(true);
    setBanner(null);
    try {
      const session = await loginPipeline(username, loginPassword);
      setAuthUser(session.username || username);
      setApiSecret(SESSION_AUTH_PLACEHOLDER);
      setLoginPassword('');
    } catch (error) {
      setBanner({ type: 'error', text: '凭据无效，请检查账号密码。' });
    } finally {
      setAuthSubmitting(false);
    }
  }

  async function handleLogout() {
    setAuthSubmitting(true);
    try {
      await logoutPipeline();
      setAuthUser(null);
      setApiSecret('');
      setAccounts([]);
      setPagination(null);
      setSelectedOpportunityId(null);
      setSelectedAccountId('');
      setOpportunities([]);
      setDraft(null);
      setProfileForm(EMPTY_PROFILE);
      setProfileUpdatedAt('');
      setProfileVersions([]);
      setSynthesisReport(null);
      setRealtimeSession(null);
      setBanner(null);
    } catch (error) {
      setBanner({ type: 'error', text: '退出登录失败' });
    } finally {
      setAuthSubmitting(false);
    }
  }

  async function loadOpportunities(page = 1) {
    if (!apiSecret.trim()) return;
    setLoadingOpportunities(true);
    try {
      const result = await listOpportunities(apiSecret.trim(), {
        status: statusFilter,
        accountId: accountIdFilter.trim() || undefined,
        page,
        pageSize: DEFAULT_PAGE_SIZE,
      });
      setOpportunities(result.items);
      setPagination(result.pagination);
    } catch (error) {
      setBanner({ type: 'error', text: '加载创作机会失败' });
    } finally {
      setLoadingOpportunities(false);
    }
  }

  async function handleSync(refresh = false) {
    if (!apiSecret.trim() || !selectedAccountId) return;
    setSyncing(true);
    try {
      const result = await computeRealtimeOpportunities(apiSecret.trim(), {
        accountId: selectedAccountId, topN: realtimeTopN, refresh,
      });
      setRealtimeSession(result);
      setBanner({ type: 'success', text: `同步完成：已发现 ${result.counts.storedCount} 个新机会。` });
    } catch (error) {
      setBanner({ type: 'error', text: '同步机会失败' });
    } finally {
      setSyncing(false);
    }
  }

  async function handleGenerateFromRealtimeSession() {
    if (!apiSecret.trim() || !realtimeSession?.sessionId) return;
    setGeneratingRealtime(true);
    try {
      const generated = await generateRealtimeDraft(apiSecret.trim(), {
        accountId: selectedAccountId, sessionId: realtimeSession.sessionId,
      });
      await loadDraft(generated.draft.draftId);
      setBanner({ type: 'success', text: '已基于当前会话生成草稿。' });
      void loadOpportunities(pagination?.page || 1);
    } catch (error) {
      setBanner({ type: 'error', text: '生成失败' });
    } finally {
      setGeneratingRealtime(false);
    }
  }

  async function loadDraft(draftId: string) {
    setLoadingDraft(true);
    try {
      const data = await getDraftDetail(apiSecret.trim(), draftId);
      setDraft(data);
      if (data.synthesisReportId) {
        try {
          const report = await getDraftSynthesisReport(apiSecret.trim(), draftId);
          setSynthesisReport(report);
        } catch { setSynthesisReport(null); }
      }
    } catch (error) {
      setBanner({ type: 'error', text: '加载草稿详情失败' });
    } finally {
      setLoadingDraft(false);
    }
  }

  async function handleGenerate(opportunityId: string) {
    setGeneratingOpportunityId(opportunityId);
    try {
      const generated = await generateDraft(apiSecret.trim(), opportunityId, {
        profileOverride: buildProfilePayload(profileForm),
      });
      await loadDraft(generated.draftId);
      void loadOpportunities(pagination?.page || 1);
    } catch (error) {
      setBanner({ type: 'error', text: '生成草稿失败' });
    } finally {
      setGeneratingOpportunityId(null);
    }
  }

  async function handleRegenerate() {
    if (!draft) return;
    setRegenerating(true);
    try {
      const generated = await regenerateDraft(apiSecret.trim(), draft.id);
      await loadDraft(generated.draftId);
    } catch (error) {
      setBanner({ type: 'error', text: '重新生成失败' });
    } finally {
      setRegenerating(false);
    }
  }

  async function handleAutoGenerate() {
    if (!selectedAccountId) return;
    setAutoGenerating(true);
    try {
      const generated = await autoGenerateDraft(apiSecret.trim(), selectedAccountId, 'manual');
      await loadDraft(generated.draftId);
      void loadOpportunities(pagination?.page || 1);
    } catch (error) {
      setBanner({ type: 'error', text: '自动生产流程失败' });
    } finally {
      setAutoGenerating(false);
    }
  }

  async function handlePlanAssets() {
    if (!draft) return;
    setPlanningAssets(true);
    try {
      await planDraftAssets(apiSecret.trim(), draft.id, { imageCount: 4, stylePreset: 'news-analysis' });
      await loadDraft(draft.id);
    } catch (error) {
      setBanner({ type: 'error', text: '规划配图失败' });
    } finally {
      setPlanningAssets(false);
    }
  }

  async function handleCopy() {
    if (!draft?.content) return;
    try {
      await navigator.clipboard.writeText(draft.content);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    } catch (error) {
      setBanner({ type: 'error', text: '复制失败' });
    }
  }

  async function handlePublish() {
    if (!draft) return;
    setPublishing(true);
    try {
      await publishWechatDraft(apiSecret.trim(), draft.id, true);
      await loadDraft(draft.id);
      setBanner({ type: 'success', text: '发布任务已提交' });
    } catch (error) {
      setBanner({ type: 'error', text: '提交发布失败' });
    } finally {
      setPublishing(false);
    }
  }

  async function handleRetry(jobId: string, allowReview: boolean) {
    if (!draft) return;
    setRetryingJobId(jobId);
    try {
      await retryPublishJob(apiSecret.trim(), jobId, allowReview);
      await loadDraft(draft.id);
    } catch (error) {
      setBanner({ type: 'error', text: '重试任务失败' });
    } finally {
      setRetryingJobId(null);
    }
  }

  async function handleSaveProfile() {
    if (!selectedAccountId) return;
    setSavingProfile(true);
    try {
      const result = await updateAccountProfile(apiSecret.trim(), selectedAccountId, buildProfilePayload(profileForm));
      setProfileForm(mapProfileForm(result.profile));
      setProfileUpdatedAt(result.profile.updatedAt);
      setBanner({ type: 'success', text: '账号定位配置已更新。' });
    } catch (error) {
      setBanner({ type: 'error', text: '更新失败' });
    } finally {
      setSavingProfile(false);
    }
  }

  async function handleRollback(versionId: string) {
    setRollingBackVersionId(versionId);
    try {
      const result = await rollbackAccountProfile(apiSecret.trim(), selectedAccountId, versionId);
      setProfileForm(mapProfileForm(result.profile));
      setBanner({ type: 'success', text: '已回滚到选定版本。' });
    } catch (error) {
      setBanner({ type: 'error', text: '回滚失败' });
    } finally {
      setRollingBackVersionId(null);
    }
  }

  if (authChecking) {
    return (
      <div className="flex items-center justify-center h-48 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-3 text-slate-400 text-sm font-bold">
          <div className="w-4 h-4 border-2 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin"></div>
          正在验证身份...
        </div>
      </div>
    );
  }

  if (!authUser) {
    return (
      <div className="max-w-md mx-auto bg-white dark:bg-slate-900 p-8 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="mb-8 text-center">
          <h2 className="text-xl font-black tracking-tight mb-2">访问控制</h2>
          <p className="text-sm text-slate-500 font-medium">请登录以进入生产引擎工作台</p>
        </div>
        <div className="space-y-4">
          <input
            value={loginUsername}
            onChange={(e) => setLoginUsername(e.target.value)}
            placeholder="账号名称"
            className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm font-medium transition-all"
          />
          <input
            type="password"
            value={loginPassword}
            onChange={(e) => setLoginPassword(e.target.value)}
            placeholder="登录密码"
            className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm font-medium transition-all"
            onKeyDown={(e) => e.key === 'Enter' && handleLogin()}
          />
          <button
            onClick={handleLogin}
            disabled={authSubmitting}
            className="w-full py-3 bg-indigo-600 text-white rounded-xl text-sm font-black tracking-wider hover:bg-indigo-700 disabled:opacity-50 transition-all shadow-lg shadow-indigo-500/20"
          >
            {authSubmitting ? '登录中...' : '继续访问'}
          </button>
        </div>
        {banner && (
          <div className={`mt-6 px-4 py-3 rounded-xl text-xs font-bold border ${bannerClass(banner.type)}`}>
            {banner.text}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-indigo-50 dark:bg-indigo-500/10 rounded-lg">
            <svg className="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
          </div>
          <div>
            <h2 className="text-sm font-black uppercase tracking-tight">内容生产工作台</h2>
            <p className="text-[10px] font-bold text-slate-400">当前登录: {authUser}</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => void loadOpportunities(1)}
            disabled={loadingOpportunities}
            className="px-3 py-1.5 bg-slate-100 dark:bg-slate-800 text-[10px] font-black rounded-lg hover:bg-slate-200 transition-colors uppercase"
          >
            {loadingOpportunities ? '加载中' : '刷新机会'}
          </button>
          <Link
            href="/accounts/settings"
            className="px-3 py-1.5 bg-slate-100 dark:bg-slate-800 text-[10px] font-black rounded-lg hover:bg-slate-200 transition-colors uppercase"
          >
            账号管理
          </Link>
          <button
            onClick={handleLogout}
            className="px-3 py-1.5 text-[10px] font-black text-red-500 bg-red-50 dark:bg-red-500/10 rounded-lg hover:bg-red-100 transition-colors uppercase"
          >
            退出登录
          </button>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
                机会发现与选题合成
              </h3>
              <button
                onClick={() => setShowAccountSettings(!showAccountSettings)}
                className="text-[10px] font-black text-indigo-600 hover:underline uppercase"
              >
                {showAccountSettings ? '隐藏配置' : '展开配置'}
              </button>
            </div>

            <div className={`space-y-6 transition-all ${showAccountSettings ? 'block' : 'hidden'}`}>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase">目标受众</label>
                  <input
                    value={profileForm.audience}
                    onChange={(e) => setProfileForm(p => ({ ...p, audience: e.target.value }))}
                    className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm outline-none"
                    placeholder="如：科技数码爱好者"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase">风格语气定位</label>
                  <input
                    value={profileForm.tone}
                    onChange={(e) => setProfileForm(p => ({ ...p, tone: e.target.value }))}
                    className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm outline-none"
                    placeholder="如：硬核、专业、锐利"
                  />
                </div>
              </div>
              <div className="flex gap-2 pt-2">
                <button
                  onClick={handleSaveProfile}
                  disabled={savingProfile || !selectedAccountId}
                  className="px-4 py-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-[11px] font-black rounded-xl uppercase hover:opacity-90 transition-all"
                >
                  {savingProfile ? '正在保存' : '保存定位配置'}
                </button>
              </div>
              <div className="h-[1px] bg-slate-100 dark:bg-slate-800"></div>
            </div>

            <div className="grid gap-4 md:grid-cols-3 mt-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase">当前生产账号</label>
                <select
                  value={selectedAccountId}
                  onChange={(e) => setSelectedAccountId(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm outline-none font-medium appearance-none"
                >
                  <option value="">请选择账号</option>
                  {accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase">机会状态筛选</label>
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value as OpportunityStatus)}
                  className="w-full bg-slate-50 dark:bg-slate-800 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm outline-none font-medium appearance-none"
                >
                  {OPPORTUNITY_STATUS_OPTIONS.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <div className="flex items-end pb-0.5">
                <button
                  onClick={() => handleSync(false)}
                  disabled={syncing || !selectedAccountId}
                  className="w-full py-2 bg-indigo-600 text-white text-[11px] font-black rounded-xl uppercase hover:bg-indigo-700 transition-all shadow-md shadow-indigo-500/10"
                >
                  {syncing ? '检索中...' : '同步创作机会'}
                </button>
              </div>
            </div>
          </div>

          <div className="grid gap-6 xl:grid-cols-[1fr_380px]">
            <OpportunityList
              opportunities={opportunities}
              loading={loadingOpportunities}
              selectedOpportunityId={selectedOpportunityId}
              generatingOpportunityId={generatingOpportunityId}
              onSelectOpportunity={(id) => {
                setSelectedOpportunityId(id);
                const p = opportunities.find(o => o.id === id);
                if (p) setSelectedAccountId(p.accountId);
              }}
              onGenerateDraft={handleGenerate}
            />
            <div className="space-y-6">
              <DraftPreview
                draft={draft}
                loading={loadingDraft}
                publishing={publishing}
                regenerating={regenerating}
                planningAssets={planningAssets}
                copied={copied}
                onCopy={handleCopy}
                onRegenerate={handleRegenerate}
                onPlanAssets={handlePlanAssets}
                onPublish={handlePublish}
              />
              <PublishJobList
                jobs={draft?.publishJobs || []}
                retryingJobId={retryingJobId}
                onRetry={handleRetry}
              />
            </div>
          </div>
        </div>

        <aside className="space-y-6">
          <div className="bg-slate-900 dark:bg-slate-800 text-white p-6 rounded-2xl shadow-xl">
            <h4 className="text-[10px] font-black tracking-widest text-indigo-400 mb-4 uppercase">智能流水线</h4>
            <div className="space-y-4">
              <button
                onClick={handleAutoGenerate}
                disabled={autoGenerating || !selectedAccountId}
                className="w-full py-3 bg-white text-slate-900 rounded-xl text-xs font-black uppercase hover:bg-slate-100 transition-all flex items-center justify-center gap-2"
              >
                {autoGenerating ? (
                  <div className="w-3 h-3 border-2 border-slate-900/20 border-t-slate-900 rounded-full animate-spin"></div>
                ) : (
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                )}
                全自动 AI 创作
              </button>
              <p className="text-[10px] text-slate-400 font-bold leading-relaxed">
                触发端到端 AI 选题流程，基于当前实时热榜为该账号自动生产高匹配度稿件。
              </p>
            </div>
          </div>

          {banner && (
            <div className={`px-4 py-3 rounded-xl text-[10px] font-bold border animate-in slide-in-from-right-2 duration-300 ${bannerClass(banner.type)}`}>
              <div className="flex gap-2">
                <svg className="w-4 h-4 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                {banner.text}
              </div>
            </div>
          )}

          {synthesisReport && (
            <div className="bg-white dark:bg-slate-900 p-5 rounded-2xl border border-slate-200 dark:border-slate-800">
              <h4 className="text-[10px] font-black text-slate-400 mb-4 uppercase">选题合成溯源</h4>
              <div className="space-y-3">
                <div className="text-xs font-bold leading-snug">{synthesisReport.report.finalTopic}</div>
                <p className="text-[10px] text-slate-500 leading-relaxed italic">
                  &ldquo;{synthesisReport.report.oneLiner}&rdquo;
                </p>
              </div>
            </div>
          )}
        </aside>
      </div>
    </div>
  );
}
