import { createHash } from 'crypto';
import { lookup } from 'dns/promises';
import { isIP } from 'net';
import {
  AutoGenerateJobStatus,
  AutoGenerateTriggerMode,
  DraftStatus,
  OpportunityStatus,
  Prisma,
} from '@prisma/client';
import { prisma } from '@/lib/db';
import { getLLMProvider } from '@/lib/providers/llm';
import type {
  AutoGenerateDraftResult,
  TopicEvidence,
  TopicResearchData,
  TopicSynthesisReportData,
} from '@/types/pipeline';
import { generateDraftFromOpportunity } from '@/lib/pipeline/draft-service';
import { getOrCreateAccountProfile } from '@/lib/pipeline/profile-service';
import { computeRealtimeOpportunitySession } from '@/lib/pipeline/realtime-opportunity-service';

const DEFAULT_CANDIDATE_LIMIT = 10;
const RESEARCH_MAX_RETRY = 2;
const RESEARCH_MAX_SOURCE_COUNT = 6;
const FETCH_TIMEOUT_MS = 8000;
const FETCH_MAX_BYTES = 1024 * 1024; // 1MB
const AUTO_GENERATE_TRIGGER_WINDOW_DEFAULT_MINUTES = 9;

interface CandidatePoolItem {
  id: string;
  score: number;
  reasons: string[];
  title: string;
  evidences: TopicEvidence[];
}

function stripHtml(input: string) {
  return input
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function detectLanguage(text: string): 'zh' | 'en' | 'other' {
  if (/[\u4e00-\u9fa5]/.test(text)) {
    return 'zh';
  }
  if (/[a-zA-Z]/.test(text)) {
    return 'en';
  }

  return 'other';
}

function buildRunKey(params: {
  accountId: string;
  triggerMode: AutoGenerateTriggerMode;
  scheduledFor?: Date;
  scheduleDateKey?: string;
}) {
  if (params.triggerMode === AutoGenerateTriggerMode.SCHEDULED) {
    const dateKey =
      params.scheduleDateKey ||
      (params.scheduledFor || new Date()).toISOString().slice(0, 10);
    return `${params.accountId}:${params.triggerMode}:${dateKey}`;
  }

  return `${params.accountId}:${params.triggerMode}:${Date.now()}`;
}

function toTopicEvidenceArray(value: Prisma.JsonValue | null | undefined) {
  if (!Array.isArray(value)) {
    return [] as TopicEvidence[];
  }

  return value
    .filter((item) => item && typeof item === 'object')
    .map((item) => {
      const row = item as Record<string, unknown>;
      return {
        platform: typeof row.platform === 'string' ? row.platform : 'unknown',
        title: typeof row.title === 'string' ? row.title : 'unknown',
        url: typeof row.url === 'string' ? row.url : undefined,
        rank: typeof row.rank === 'number' ? row.rank : 0,
        hotValue: typeof row.hotValue === 'number' ? row.hotValue : undefined,
        snapshotAt:
          typeof row.snapshotAt === 'string' ? row.snapshotAt : new Date().toISOString(),
      };
    })
    .filter((item) => item.title !== 'unknown');
}

function toStringArray(value: Prisma.JsonValue | null | undefined) {
  if (!Array.isArray(value)) {
    return [] as string[];
  }

  return value
    .filter((item): item is string => typeof item === 'string')
    .map((item) => item.trim())
    .filter(Boolean);
}

async function buildCandidatePoolFromRealtime(accountId: string): Promise<CandidatePoolItem[]> {
  const compute = await computeRealtimeOpportunitySession({
    accountId,
    topN: DEFAULT_CANDIDATE_LIMIT,
    refresh: false,
  });

  const session = await prisma.realtimeOpportunitySession.findUnique({
    where: {
      id: compute.sessionId,
    },
    include: {
      items: {
        orderBy: [{ weightedScore: 'desc' }, { createdAt: 'asc' }],
        take: DEFAULT_CANDIDATE_LIMIT,
      },
    },
  });

  if (!session || session.items.length === 0) {
    return [];
  }

  return session.items.map((item) => ({
    id: `rt:${item.fingerprint}`,
    score: item.weightedScore,
    reasons: toStringArray(item.reasons),
    title: item.title,
    evidences: toTopicEvidenceArray(item.evidences),
  }));
}

function parseReportContent(raw: string) {
  try {
    const parsed = JSON.parse(raw) as {
      oneLiner?: string;
      mergeRationale?: string[];
      selectionRationale?: string[];
      accountFitReason?: string;
      selectedOpportunityIds?: string[];
      traceScores?: Record<string, number>;
    };

    return {
      oneLiner: typeof parsed.oneLiner === 'string' ? parsed.oneLiner : undefined,
      mergeRationale: Array.isArray(parsed.mergeRationale)
        ? parsed.mergeRationale.filter((item): item is string => typeof item === 'string')
        : [],
      selectionRationale: Array.isArray(parsed.selectionRationale)
        ? parsed.selectionRationale.filter((item): item is string => typeof item === 'string')
        : [],
      accountFitReason:
        typeof parsed.accountFitReason === 'string' ? parsed.accountFitReason : undefined,
      selectedOpportunityIds: Array.isArray(parsed.selectedOpportunityIds)
        ? parsed.selectedOpportunityIds.filter((item): item is string => typeof item === 'string')
        : [],
      traceScores:
        parsed.traceScores && typeof parsed.traceScores === 'object'
          ? Object.fromEntries(
              Object.entries(parsed.traceScores)
                .map(([key, value]) => [key, Number(value)])
                .filter(([, value]) => Number.isFinite(value))
            )
          : {},
    };
  } catch {
    return {
      oneLiner: undefined,
      mergeRationale: [] as string[],
      selectionRationale: [] as string[],
      accountFitReason: undefined,
      selectedOpportunityIds: [] as string[],
      traceScores: {} as Record<string, number>,
    };
  }
}

async function synthesizeTopic(params: {
  accountName: string;
  profileText: string;
  opportunities: Array<{
    id: string;
    score: number;
    reasons: string[];
    title: string;
    evidences: TopicEvidence[];
  }>;
}) {
  const provider = getLLMProvider();

  const candidateText = params.opportunities
    .map((opportunity, index) => {
      const evidenceText = opportunity.evidences
        .slice(0, 3)
        .map((item) => `- [${item.platform}] ${item.title}${item.url ? ` (${item.url})` : ''}`)
        .join('\n');

      return [
        `${index + 1}. id=${opportunity.id}`,
        `score=${opportunity.score.toFixed(1)}`,
        `title=${opportunity.title}`,
        `reasons=${opportunity.reasons.join(';')}`,
        evidenceText || '- evidence: none',
      ].join('\n');
    })
    .join('\n\n');

  const generated = await provider.generate({
    systemPrompt: [
      '你是一名中文内容策略总编。',
      '任务：把多个热点候选整合为一个可写作的凝练命题。',
      '请避免复述单条热榜标题，必须是综合提炼结果。',
    ].join('\n'),
    userPrompt: [
      `账号：${params.accountName}`,
      '账号画像：',
      params.profileText,
      '',
      '候选机会池：',
      candidateText,
      '',
      '输出约束：',
      '1) title 字段为最终命题标题；',
      '2) outline 字段放 selectedOpportunityIds；',
      '3) content 字段必须是 JSON 字符串，包含 oneLiner / mergeRationale / selectionRationale / accountFitReason / selectedOpportunityIds / traceScores。',
    ].join('\n'),
    topicTitle: '多源热点综合选题',
    accountName: params.accountName,
  });

  const parsed = parseReportContent(generated.content);
  const pickedIds =
    parsed.selectedOpportunityIds.length > 0
      ? parsed.selectedOpportunityIds
      : params.opportunities.slice(0, 3).map((item) => item.id);

  return {
    finalTopic: generated.title.trim(),
    oneLiner: parsed.oneLiner,
    mergeRationale:
      parsed.mergeRationale.length > 0
        ? parsed.mergeRationale
        : ['候选热点在事实层面具备主题连续性，可归并为同一讨论命题。'],
    selectionRationale:
      parsed.selectionRationale.length > 0
        ? parsed.selectionRationale
        : ['综合时效、热度和账号画像后，该命题综合分最高。'],
    accountFitReason: parsed.accountFitReason || '命题与账号受众痛点及增长目标匹配。',
    selectedOpportunityIds: pickedIds,
    traceScores: parsed.traceScores,
    model: generated.model,
  };
}

async function fetchSnippet(url: string) {
  const checkedUrl = await validateResearchUrl(url);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

  try {
    const response = await fetch(checkedUrl, {
      headers: {
        'User-Agent': 'TrendPipelineBot/1.0',
        Accept: 'text/html,application/json;q=0.9,*/*;q=0.8',
      },
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const raw = await readResponseBodyWithLimit(response, FETCH_MAX_BYTES);
    const text = stripHtml(raw);
    return text.slice(0, 800);
  } finally {
    clearTimeout(timeout);
  }
}

function isPrivateIpv4(ip: string) {
  const parts = ip.split('.').map((item) => Number(item));
  if (parts.length !== 4 || parts.some((item) => Number.isNaN(item))) {
    return true;
  }

  if (parts[0] === 10 || parts[0] === 127 || parts[0] === 0) {
    return true;
  }
  if (parts[0] === 169 && parts[1] === 254) {
    return true;
  }
  if (parts[0] === 192 && parts[1] === 168) {
    return true;
  }
  if (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) {
    return true;
  }

  return false;
}

function isPrivateIpv6(ip: string) {
  const normalized = ip.toLowerCase();
  return (
    normalized === '::1' ||
    normalized.startsWith('fc') ||
    normalized.startsWith('fd') ||
    normalized.startsWith('fe80:')
  );
}

async function validateResearchUrl(raw: string) {
  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    throw new Error('Invalid research URL.');
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Unsupported research URL protocol.');
  }

  const hostname = parsed.hostname.toLowerCase();
  if (
    hostname === 'localhost' ||
    hostname.endsWith('.localhost') ||
    hostname.endsWith('.local')
  ) {
    throw new Error('Blocked research URL host.');
  }

  const ipType = isIP(hostname);
  if (ipType === 4 && isPrivateIpv4(hostname)) {
    throw new Error('Blocked private IPv4 research URL.');
  }
  if (ipType === 6 && isPrivateIpv6(hostname)) {
    throw new Error('Blocked private IPv6 research URL.');
  }

  const resolved = await lookup(hostname, { all: true, verbatim: true });
  if (!resolved || resolved.length === 0) {
    throw new Error('Research URL DNS resolution failed.');
  }

  const privateHit = resolved.some((record) => {
    if (record.family === 4) {
      return isPrivateIpv4(record.address);
    }
    if (record.family === 6) {
      return isPrivateIpv6(record.address);
    }
    return true;
  });

  if (privateHit) {
    throw new Error('Blocked private network research URL.');
  }

  return parsed.toString();
}

async function readResponseBodyWithLimit(response: Response, maxBytes: number) {
  const contentLengthHeader = response.headers.get('content-length');
  if (contentLengthHeader) {
    const contentLength = Number(contentLengthHeader);
    if (Number.isFinite(contentLength) && contentLength > maxBytes) {
      throw new Error('Research response too large.');
    }
  }

  if (!response.body) {
    return '';
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let totalBytes = 0;
  let text = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }

    const chunk = value || new Uint8Array();
    totalBytes += chunk.byteLength;
    if (totalBytes > maxBytes) {
      throw new Error('Research response exceeded size limit.');
    }

    text += decoder.decode(chunk, { stream: true });
  }

  text += decoder.decode();
  return text;
}

async function deepResearch(params: {
  accountId: string;
  synthesisReportId: string;
  finalTopic: string;
  candidateEvidences: TopicEvidence[];
}): Promise<TopicResearchData> {
  const sourceUrls = Array.from(
    new Set(
      params.candidateEvidences
        .map((item) => item.url)
        .filter((item): item is string => typeof item === 'string' && item.startsWith('http'))
    )
  ).slice(0, RESEARCH_MAX_SOURCE_COUNT);

  const querySet = [
    `${params.finalTopic} 深度解析`,
    `${params.finalTopic} latest analysis`,
    `${params.finalTopic} background and impact`,
  ];

  let retryCount = 0;
  let sources: Array<{ title: string; url?: string; snippet: string; language: 'zh' | 'en' | 'other' }> = [];

  while (retryCount <= RESEARCH_MAX_RETRY) {
    try {
      const fetched = await Promise.all(
        sourceUrls.map(async (url) => {
          const snippet = await fetchSnippet(url);
          return {
            title: new URL(url).hostname,
            url,
            snippet,
            language: detectLanguage(snippet),
          } as const;
        })
      );

      sources = fetched.filter((item) => item.snippet.trim().length > 0);
      if (sources.length > 0) {
        break;
      }
    } catch {
      // Continue retries before fallback.
    }

    retryCount += 1;
  }

  const fallbackUsed = sources.length === 0;
  if (fallbackUsed) {
    sources = params.candidateEvidences.slice(0, 5).map((item) => ({
      title: item.title,
      url: item.url,
      snippet: `[fallback] ${item.title}`,
      language: detectLanguage(item.title),
    }));
  }

  const created = await prisma.topicResearch.create({
    data: {
      accountId: params.accountId,
      synthesisReportId: params.synthesisReportId,
      querySet: querySet as unknown as Prisma.InputJsonValue,
      sources: sources as unknown as Prisma.InputJsonValue,
      languageMix: 'zh-en',
      retryCount,
      fallbackUsed,
    },
  });

  return {
    id: created.id,
    accountId: created.accountId,
    synthesisReportId: created.synthesisReportId,
    querySet,
    sources,
    languageMix: created.languageMix,
    retryCount: created.retryCount,
    fallbackUsed: created.fallbackUsed,
    createdAt: created.createdAt.toISOString(),
  };
}

function mergeMetadata(
  origin: Prisma.JsonValue | null,
  patches: Record<string, unknown>
): Prisma.InputJsonValue {
  const base = origin && typeof origin === 'object' ? { ...(origin as Record<string, unknown>) } : {};
  return {
    ...base,
    ...patches,
  } as unknown as Prisma.InputJsonValue;
}

function formatProfileText(profile: {
  audience: string;
  tone: string;
  growthGoal: string;
  painPoints: string[];
  contentPromise?: string;
  forbiddenTopics: string[];
  ctaStyle?: string;
  preferredLength: number;
}) {
  return [
    `目标读者：${profile.audience}`,
    `语气风格：${profile.tone}`,
    `增长目标：${profile.growthGoal}`,
    `痛点：${profile.painPoints.join('；') || '-'}`,
    `内容承诺：${profile.contentPromise || '-'}`,
    `禁区：${profile.forbiddenTopics.join('；') || '-'}`,
    `CTA：${profile.ctaStyle || '-'}`,
    `目标字数：${profile.preferredLength}`,
  ].join('\n');
}

export async function autoGenerateDraftForAccount(params: {
  accountId: string;
  triggerMode: 'manual' | 'scheduled';
  scheduledFor?: Date;
  scheduleDateKey?: string;
}): Promise<AutoGenerateDraftResult> {
  const triggerMode =
    params.triggerMode === 'scheduled'
      ? AutoGenerateTriggerMode.SCHEDULED
      : AutoGenerateTriggerMode.MANUAL;
  const runKey = buildRunKey({
    accountId: params.accountId,
    triggerMode,
    scheduledFor: params.scheduledFor,
    scheduleDateKey: params.scheduleDateKey,
  });

  let job: { id: string } | null = null;

  if (triggerMode === AutoGenerateTriggerMode.SCHEDULED) {
    const existing = await prisma.autoGenerateJob.findUnique({
      where: {
        runKey,
      },
      select: {
        id: true,
        draftId: true,
        synthesisReportId: true,
        status: true,
        fallbackUsed: true,
      },
    });

    if (existing) {
      if (
        existing.status === AutoGenerateJobStatus.SUCCESS &&
        existing.draftId &&
        existing.synthesisReportId
      ) {
        const draft = await prisma.draft.findUnique({
          where: {
            id: existing.draftId,
          },
          select: {
            status: true,
          },
        });

        return {
          jobId: existing.id,
          accountId: params.accountId,
          draftId: existing.draftId,
          synthesisReportId: existing.synthesisReportId,
          status: draft?.status || DraftStatus.READY,
          fallbackUsed: existing.fallbackUsed,
          triggerMode,
        };
      }

      if (existing.status === AutoGenerateJobStatus.RUNNING) {
        throw new Error('Scheduled job already running.');
      }

      const updated = await prisma.autoGenerateJob.update({
        where: {
          id: existing.id,
        },
        data: {
          status: AutoGenerateJobStatus.RUNNING,
          startedAt: new Date(),
          finishedAt: null,
          error: null,
          fallbackUsed: false,
        },
        select: {
          id: true,
        },
      });
      job = updated;
    }
  }

  if (!job) {
    const created = await prisma.autoGenerateJob.create({
      data: {
        accountId: params.accountId,
        triggerMode,
        runKey,
        status: AutoGenerateJobStatus.RUNNING,
        startedAt: new Date(),
        scheduledFor: params.scheduledFor,
      },
      select: {
        id: true,
      },
    });
    job = created;
  }

  try {
    const [account, profile, opportunities] = await Promise.all([
      prisma.account.findUnique({
        where: { id: params.accountId },
        select: {
          id: true,
          name: true,
          isActive: true,
        },
      }),
      getOrCreateAccountProfile(params.accountId),
      prisma.opportunity.findMany({
        where: {
          accountId: params.accountId,
          status: {
            in: [OpportunityStatus.NEW, OpportunityStatus.SELECTED],
          },
        },
        include: {
          topicCluster: true,
        },
        orderBy: [{ score: 'desc' }, { updatedAt: 'desc' }],
        take: DEFAULT_CANDIDATE_LIMIT,
      }),
    ]);

    if (!account || !account.isActive) {
      throw new Error('Account not found or inactive.');
    }

    let candidatePool: CandidatePoolItem[] = opportunities.map((opportunity) => ({
      id: opportunity.id,
      score: opportunity.score,
      reasons: Array.isArray(opportunity.reasons)
        ? opportunity.reasons.filter((item): item is string => typeof item === 'string')
        : [],
      title: opportunity.topicCluster.title,
      evidences: toTopicEvidenceArray(opportunity.topicCluster.evidences),
    }));

    if (candidatePool.length === 0) {
      candidatePool = await buildCandidatePoolFromRealtime(params.accountId);
    }

    if (candidatePool.length === 0) {
      throw new Error('No candidate opportunities found for this account.');
    }

    const synthesized = await synthesizeTopic({
      accountName: account.name,
      profileText: formatProfileText(profile),
      opportunities: candidatePool,
    });

    const selectedIds = new Set(synthesized.selectedOpportunityIds);
    const sourceItems = candidatePool
      .filter((item) => selectedIds.size === 0 || selectedIds.has(item.id))
      .slice(0, 6)
      .map((item) => ({
        platform: item.evidences[0]?.platform || 'unknown',
        title: item.title,
        url: item.evidences[0]?.url,
        reason: item.reasons[0] || 'score-top-candidate',
        score: item.score,
      }));

    const traceScores =
      Object.keys(synthesized.traceScores).length > 0
        ? synthesized.traceScores
        : {
            topicPoolTop: candidatePool[0]?.score || 0,
            poolAvg:
              candidatePool.reduce((sum, item) => sum + item.score, 0) /
              Math.max(1, candidatePool.length),
          };

    const synthesisReport = await prisma.topicSynthesisReport.create({
      data: {
        accountId: params.accountId,
        finalTopic: synthesized.finalTopic,
        oneLiner: synthesized.oneLiner,
        sourceItems: sourceItems as unknown as Prisma.InputJsonValue,
        mergeRationale: synthesized.mergeRationale as unknown as Prisma.InputJsonValue,
        selectionRationale: synthesized.selectionRationale as unknown as Prisma.InputJsonValue,
        accountFitReason: synthesized.accountFitReason,
        traceScores: traceScores as unknown as Prisma.InputJsonValue,
      },
    });

    const candidateEvidences = candidatePool.flatMap((item) => item.evidences);
    const research = await deepResearch({
      accountId: params.accountId,
      synthesisReportId: synthesisReport.id,
      finalTopic: synthesized.finalTopic,
      candidateEvidences,
    });

    const combinedEvidence = Array.from(
      new Map(
        [
          ...candidateEvidences,
          ...research.sources.map((source, index) => ({
            platform: source.language === 'zh' ? 'web-zh' : source.language === 'en' ? 'web-en' : 'web',
            title: source.title,
            url: source.url,
            rank: index + 1,
            hotValue: undefined,
            snapshotAt: new Date().toISOString(),
          })),
        ].map((item) => [`${item.platform}:${item.title}:${item.url || ''}`, item])
      ).values()
    ).slice(0, 12);

    const fingerprint = createHash('sha256')
      .update(`${params.accountId}:${synthesized.finalTopic}`)
      .digest('hex')
      .slice(0, 40);

    const now = new Date();
    const topicCluster = await prisma.topicCluster.upsert({
      where: {
        fingerprint,
      },
      update: {
        title: synthesized.finalTopic,
        keywords: synthesized.finalTopic.split(/\s+/).slice(0, 10),
        evidences: combinedEvidence as unknown as Prisma.InputJsonValue,
        resonanceCount: new Set(combinedEvidence.map((item) => item.platform)).size,
        growthScore: traceScores.topicPoolTop || candidatePool[0]?.score || 60,
        latestSnapshotAt: now,
        windowStart: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
        windowEnd: now,
      },
      create: {
        fingerprint,
        title: synthesized.finalTopic,
        keywords: synthesized.finalTopic.split(/\s+/).slice(0, 10),
        evidences: combinedEvidence as unknown as Prisma.InputJsonValue,
        resonanceCount: new Set(combinedEvidence.map((item) => item.platform)).size,
        growthScore: traceScores.topicPoolTop || candidatePool[0]?.score || 60,
        latestSnapshotAt: now,
        windowStart: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
        windowEnd: now,
      },
    });

    const opportunity = await prisma.opportunity.upsert({
      where: {
        topicClusterId_accountId: {
          topicClusterId: topicCluster.id,
          accountId: params.accountId,
        },
      },
      update: {
        score: candidatePool[0]?.score || 60,
        layeredScore: traceScores as unknown as Prisma.InputJsonValue,
        personaFitScore: 80,
        riskPrecheckScore: 80,
        reasons: synthesized.selectionRationale as unknown as Prisma.InputJsonValue,
        status: OpportunityStatus.NEW,
        expiresAt: new Date(now.getTime() + 6 * 60 * 60 * 1000),
      },
      create: {
        accountId: params.accountId,
        topicClusterId: topicCluster.id,
        score: candidatePool[0]?.score || 60,
        layeredScore: traceScores as unknown as Prisma.InputJsonValue,
        personaFitScore: 80,
        riskPrecheckScore: 80,
        reasons: synthesized.selectionRationale as unknown as Prisma.InputJsonValue,
        status: OpportunityStatus.NEW,
        expiresAt: new Date(now.getTime() + 6 * 60 * 60 * 1000),
      },
    });

    const draftResult = await generateDraftFromOpportunity(opportunity.id);

    const existingDraft = await prisma.draft.findUnique({
      where: {
        id: draftResult.draftId,
      },
      select: {
        metadata: true,
      },
    });

    await prisma.draft.update({
      where: {
        id: draftResult.draftId,
      },
      data: {
        synthesisReportId: synthesisReport.id,
        metadata: mergeMetadata(existingDraft?.metadata as Prisma.JsonValue | null, {
          topicSynthesis: {
            reportId: synthesisReport.id,
            finalTopic: synthesisReport.finalTopic,
            model: synthesized.model,
            sourceItems,
            mergeRationale: synthesized.mergeRationale,
            selectionRationale: synthesized.selectionRationale,
            accountFitReason: synthesized.accountFitReason,
            traceScores,
          },
          deepResearch: {
            researchId: research.id,
            querySet: research.querySet,
            sourceCount: research.sources.length,
            fallbackUsed: research.fallbackUsed,
            retryCount: research.retryCount,
          },
        }),
      },
    });

    await prisma.autoGenerateJob.update({
      where: {
        id: job.id,
      },
      data: {
        synthesisReportId: synthesisReport.id,
        draftId: draftResult.draftId,
        status: AutoGenerateJobStatus.SUCCESS,
        fallbackUsed: research.fallbackUsed,
        finishedAt: new Date(),
      },
    });

    await prisma.account.update({
      where: {
        id: params.accountId,
      },
      data: {
        lastAutoGenerateAt: new Date(),
      },
    });

    return {
      jobId: job.id,
      accountId: params.accountId,
      draftId: draftResult.draftId,
      synthesisReportId: synthesisReport.id,
      status: draftResult.status,
      fallbackUsed: research.fallbackUsed,
      triggerMode,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';

    await prisma.autoGenerateJob.update({
      where: {
        id: job.id,
      },
      data: {
        status: AutoGenerateJobStatus.FAILED,
        error: message,
        finishedAt: new Date(),
      },
    });

    throw error;
  }
}

function toLocalDateParts(now: Date, timeZone: string) {
  const formatter = new Intl.DateTimeFormat('sv-SE', {
    timeZone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });

  const parts = formatter.formatToParts(now);
  const get = (type: string) => parts.find((item) => item.type === type)?.value || '00';

  return {
    year: get('year'),
    month: get('month'),
    day: get('day'),
    hour: Number(get('hour')),
    minute: Number(get('minute')),
  };
}

function parseHHmm(value: string) {
  const match = value.match(/^([01]\d|2[0-3]):([0-5]\d)$/);
  if (!match) {
    return null;
  }

  return {
    hour: Number(match[1]),
    minute: Number(match[2]),
  };
}

function shouldTriggerNow(params: {
  now: Date;
  timeZone: string;
  publishTime: string;
  leadMinutes: number;
}) {
  const local = toLocalDateParts(params.now, params.timeZone);
  const parsed = parseHHmm(params.publishTime);

  if (!parsed) {
    return { shouldRun: false, dateKey: `${local.year}-${local.month}-${local.day}` };
  }

  const publishTotal = parsed.hour * 60 + parsed.minute;
  const triggerTotal = ((publishTotal - params.leadMinutes) % (24 * 60) + 24 * 60) % (24 * 60);
  const nowTotal = local.hour * 60 + local.minute;
  const diff = nowTotal - triggerTotal;
  const triggerWindowMinutes = Math.max(
    1,
    Math.min(
      59,
      Math.floor(
        Number(
          process.env.AUTO_GENERATE_TRIGGER_WINDOW_MINUTES ??
            AUTO_GENERATE_TRIGGER_WINDOW_DEFAULT_MINUTES
        )
      ) || AUTO_GENERATE_TRIGGER_WINDOW_DEFAULT_MINUTES
    )
  );
  const shouldRun = diff >= 0 && diff <= triggerWindowMinutes;

  return {
    shouldRun,
    dateKey: `${local.year}-${local.month}-${local.day}`,
  };
}

export async function runScheduledAutoGenerate(now = new Date()) {
  const accounts = await prisma.account.findMany({
    where: {
      isActive: true,
      autoGenerateEnabled: true,
      autoGenerateTime: {
        not: null,
      },
    },
    select: {
      id: true,
      autoGenerateTime: true,
      autoGenerateLeadMinutes: true,
      autoGenerateTimezone: true,
    },
  });

  let triggered = 0;
  let succeeded = 0;
  let failed = 0;
  let skipped = 0;

  const errors: Array<{ accountId: string; message: string }> = [];

  for (const account of accounts) {
    const publishTime = account.autoGenerateTime;
    if (!publishTime) {
      skipped += 1;
      continue;
    }

    const trigger = shouldTriggerNow({
      now,
      timeZone: account.autoGenerateTimezone,
      publishTime,
      leadMinutes: account.autoGenerateLeadMinutes,
    });

    if (!trigger.shouldRun) {
      skipped += 1;
      continue;
    }

    triggered += 1;

    try {
      await autoGenerateDraftForAccount({
        accountId: account.id,
        triggerMode: 'scheduled',
        scheduledFor: now,
        scheduleDateKey: trigger.dateKey,
      });
      succeeded += 1;
    } catch (error) {
      failed += 1;
      errors.push({
        accountId: account.id,
        message: error instanceof Error ? error.message : 'Unknown error',
      });
    }
  }

  return {
    triggered,
    succeeded,
    failed,
    skipped,
    errors,
    executedAt: now.toISOString(),
  };
}

export async function getSynthesisReportByDraftId(draftId: string): Promise<{
  report: TopicSynthesisReportData;
  researches: TopicResearchData[];
}> {
  const draft = await prisma.draft.findUnique({
    where: { id: draftId },
    select: {
      id: true,
      synthesisReportId: true,
    },
  });

  if (!draft || !draft.synthesisReportId) {
    throw new Error('Synthesis report not found for draft.');
  }

  const report = await prisma.topicSynthesisReport.findUnique({
    where: {
      id: draft.synthesisReportId,
    },
    include: {
      researches: {
        orderBy: {
          createdAt: 'desc',
        },
      },
    },
  });

  if (!report) {
    throw new Error('Synthesis report not found.');
  }

  return {
    report: {
      id: report.id,
      accountId: report.accountId,
      finalTopic: report.finalTopic,
      oneLiner: report.oneLiner || undefined,
      sourceItems: Array.isArray(report.sourceItems)
        ? report.sourceItems.filter((item): item is { platform: string; title: string; url?: string; reason: string; score?: number } => !!item && typeof item === 'object')
        : [],
      mergeRationale: Array.isArray(report.mergeRationale)
        ? report.mergeRationale.filter((item): item is string => typeof item === 'string')
        : [],
      selectionRationale: Array.isArray(report.selectionRationale)
        ? report.selectionRationale.filter((item): item is string => typeof item === 'string')
        : [],
      accountFitReason: report.accountFitReason || undefined,
      traceScores:
        report.traceScores && typeof report.traceScores === 'object'
          ? (report.traceScores as Record<string, number>)
          : {},
      riskDowngradeTrace: Array.isArray(report.riskDowngradeTrace)
        ? report.riskDowngradeTrace.filter((item): item is string => typeof item === 'string')
        : [],
      createdAt: report.createdAt.toISOString(),
      updatedAt: report.updatedAt.toISOString(),
    },
    researches: report.researches.map((research) => ({
      id: research.id,
      accountId: research.accountId,
      synthesisReportId: research.synthesisReportId,
      querySet: Array.isArray(research.querySet)
        ? research.querySet.filter((item): item is string => typeof item === 'string')
        : [],
      sources: Array.isArray(research.sources)
        ? research.sources.filter(
            (item): item is { title: string; url?: string; snippet: string; language: 'zh' | 'en' | 'other' } =>
              !!item && typeof item === 'object'
          )
        : [],
      languageMix: research.languageMix,
      retryCount: research.retryCount,
      fallbackUsed: research.fallbackUsed,
      createdAt: research.createdAt.toISOString(),
    })),
  };
}
