import { NextResponse } from 'next/server';
import { requireSecretAuth } from '@/lib/pipeline/auth';
import { autoGenerateDraftForAccount } from '@/lib/pipeline/auto-generate-service';

export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  try {
    const authError = requireSecretAuth(request, {
      envKey: 'PIPELINE_API_SECRET',
    });
    if (authError) {
      return authError;
    }

    let body: {
      accountId?: string;
      triggerMode?: 'manual' | 'scheduled';
    } = {};
    try {
      body = (await request.json()) as { accountId?: string; triggerMode?: 'manual' | 'scheduled' };
    } catch {
      body = {};
    }

    const accountId = body.accountId?.trim();
    if (!accountId) {
      return NextResponse.json(
        {
          success: false,
          errorCode: 'INVALID_INPUT',
          message: 'accountId is required.',
        },
        { status: 400 }
      );
    }

    const triggerMode = body.triggerMode === 'scheduled' ? 'scheduled' : 'manual';
    const result = await autoGenerateDraftForAccount({
      accountId,
      triggerMode,
      scheduledFor: triggerMode === 'scheduled' ? new Date() : undefined,
    });

    return NextResponse.json({
      success: true,
      data: result,
      updatedAt: new Date().toISOString(),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      {
        success: false,
        errorCode: 'AUTO_GENERATE_DRAFT_FAILED',
        message,
      },
      { status: 500 }
    );
  }
}
